USE oprahstudiodb_react;

CREATE TABLE IF NOT EXISTS project (
	project_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    client VARCHAR(100) NOT NULL,
    year YEAR NOT NULL,
    link VARCHAR(255),
    image VARCHAR(100),
	description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS tags (
	tag_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tag_name VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS category (
	category_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS project_category (
	pc_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    p_id INT NOT NULL,
    c_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (p_id) REFERENCES project (project_id) ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY (c_id) REFERENCES category (category_id) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS project_tags (
	pt_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    p_id INT NOT NULL,
    t_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (p_id) REFERENCES project (project_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (t_id) REFERENCES tags (tag_id) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=INNODB;
